dependencies:
  - name: postgresql
    version: 5.3.3
    repository: https://kubernetes-charts.storage.googleapis.com/
#  - name: redis
#    version: 3.8.1
#    repository: https://kubernetes-charts.storage.googleapis.com/
#  - name: rabbitmq
#    version: 5.5.1
#    repository: https://kubernetes-charts.storage.googleapis.com/
