{{ if .Values.manageSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.secretKey }}
  secret-key: {{ .Values.secretKey | b64enc | quote }}
  {{ else }}
  secret-key: {{ randAlphaNum 40 | b64enc | quote }}
  {{ end }}
  smtp-password: {{ default "" .Values.email.password | b64enc | quote }}
{{ end }}
